# Simple workflow for deploying static content to GitHub Pages
name: Publish to NPM

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  id-token: write

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm 9.6.0
        uses: pnpm/action-setup@v4
        with:
          version: "9.6.0"
      - name: Set up Node 20.5.0
        uses: actions/setup-node@v3
        with:
          node-version: "20.5.0"
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Test flowfiletools-js
        run: pnpm run --filter @nf2t/flowfiletools-js test
      - name: Build flowfiletools-js
        run: pnpm run --filter @nf2t/flowfiletools-js build       
      - name: Dry Run - Pack
        run: npm pack --dry-run  
        working-directory: ./libs/flowfiletools-js
